### ISSUE TITLE
Why should we trust you?

### ISSUE THREAD

**Issue by War3Evo** [tetherscript/hvdk#3]
If nobody can buy the source code, you could easily send these keys to a remote computer for passwords and bank account information.

**Comment by tetherscript** [comment]
Well, we have been in business for over 10 years selling software and we sign our drivers.  But you bring up a good question.  How can you be sure we aren't logging keystrokes with these drivers?  

The answer is simple.  It's because user-mode (and kernel-mode) drivers can't intercept keystrokes, and we wouldn't even if we could.  We get requests to install keyboard hooks for this kind of stuff so people can use keystrokes to start macros in our ControlMyJoystick software which uses these drivers, and we have consistently denied this feature request.  Anti-virus looks for this kind of thing anyways.  These drivers run under the logged-in users permissions as well.

I hope that helps.  I understand that some people won't install software unless they can see the source, and we may post the source for these drivers in the future.  Especially with the new Win10 device virtualization drivers coming along...you never know!

**Comment by Micke3rd** [comment]
@War3Evo 
1) you can't get source code from logitech or other keyboard manufacturers either. So nothing is different here.
2) You don't need to go over the virtual driver for banking or other authentication. Use your mechanical keyboard if you trust it more. Both drivers have separate channels.
