### ISSUE TITLE
TargetFrameworkVersion v3.5 is not usuable (anymore)

### ISSUE THREAD

**Issue by Micke3rd** [tetherscript/hvdk#4]
Hi Russ,
because that target is not available anymore, I dont see a option to build these examples.
The oldest available supported version from Microsoft is .Net FW 4.5.1  [https://dotnet.microsoft.com/download/visual-studio-sdks?utm_source=getdotnetsdk&utm_medium=referral](url)
But with that and younger, HVDK throws an overflow exception.

What do you suggest , how to get HVDK running ?  
Can I support you anyhow ?

**Comment by tetherscript** [comment]
Many thanks for this, and I have finally updated the .Net code so that it works in .Net 4.72 with the sample app built as 64-bit.  It was a one-liner fix.  This is the reason .Net drives me crazy.

To use DotNet 4.72 with in a 64bit app, in \common\HidCtl.cs change

IntPtr pDevicePathName = new IntPtr(DeviceInterfaceDetailData.ToInt32() + 4);

to 

IntPtr pDevicePathName = new IntPtr(DeviceInterfaceDetailData.ToInt**64**() + 4);

Cheers,

Russ

**Comment by Micke3rd** [comment]
if so simple - bad that I haven't seen it.
Thank you !
