### ISSUE TITLE
(keyboard)  Is it possible to interrupt 1 key, while another one continues to send ?

### ISSUE THREAD

**Issue by Micke3rd** [tetherscript/hvdk#8]
Hi Russ,
if I simulate navigation for a car, I have the following case where I dont know if it's possible with HVDK.

A car is driving by pressing W (forward)
To follow the street or to evade other cars I have partially to press left or right.

So I call send W without interrupt, to send it continously. While left and right need a key down **and** a key up.
But if I send a Send(0, 0, 0, 0, 0, 0, 0, 0);  every key will be canceled.
Any idea ?

thank you in advance
Micke

**Comment by tetherscript** [comment]
@Micke3rd, another great question!  So the issue here is one of state, but the state needs to be maintained by your program, not the driver.  If you have your own (modifier, padding, Key0, Key1, Key2, Key3, Key4, Key5) data structure, you can determined when the W needs to be added or removed from the state, or whether a left or right key needs to be activated.  

Once you calculate the state, you can then 'render' it to the driver.  It could be that your app needs to adjust the state 100 times per second, but you choose to render it to the driver at 60 times per seconds.

Hope that helps!

Russ

**Comment by Micke3rd** [comment]
puuh yes, frequency will be a upcoming topic too.
Got it, thank you !
